source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib', require: 'sinatra/reloader'
gem 'warden'
gem 'rethinkdb'
gem 'rest_client'
gem 'bcrypt-ruby'
gem 'capistrano', '~> 3.2.0'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
